### PR TITLE
Add pieces to parcel

### PR DESCRIPTION
**Pull request by jacobdekeizer**
## Description

Add pieces resource to configure the pieces that are going te be shipped.
I also fixed some errors in the `readme` file, like `company_name` has to be `company`, otherwise you get a 400 bad request.

## Motivation and context

This change allows a developer to configure the pieces for a parcel shipment.
The package in its current state has a harcoded shipment piece.

## How has this been tested?

I created shipments with the new pieces functionality.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] If my change requires a change to the documentation, I have updated it accordingly.
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by jacobdekeizer** [comment]
@mvdnbrk If you create multiple pieces, only 1 trackerCode and labelId is returned.
How would you like me to solve that to preserve backwards compatibility or can I make a breaking change to return an array of labels.

**Comment by mvdnbrk** [comment]
Thanks! Could you add tests for this?

**Comment by jacobdekeizer** [comment]
@mvdnbrk I added the tests.

**Comment by mvdnbrk** [comment]
Released in v0.5.0.

**Pull request merged**
