### PR TITLE
Add error details to exception message

### PR DESCRIPTION
**Pull request by jacobdekeizer**
Add error details from DHL parcel to exception message.

## Motivation and context

In the current implementation we can't see/log why something has gone wrong, because the details aren't thrown in the exception message.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] If my change requires a change to the documentation, I have updated it accordingly.
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by mvdnbrk** [comment]
A json_encoded string in the message?

**Comment by jacobdekeizer** [comment]
@mvd

**Comment by jacobdekeizer** [comment]
Sorry pressed the close button accidentally :)

**Comment by mvdnbrk** [comment]
Just a quick thought; pass the response to the exception and make it accessible for the user land.

**Comment by jacobdekeizer** [comment]
@mvdnbrk We could do that, but you still won't see what went wrong in your error message. For example if you develop in a framework like laravel of symfony and an exception is thrown, the message will be displayed on the error page. With your suggested approach there is still only a generic exception message. Also in a framework like laravel you can log exceptions, so you can trace back errors that have occurred. That's why I want to add it to the exception message, but I'm curious what you think about it.

**Comment by mvdnbrk** [comment]
@jacobdekeizer See #47 

You should catch the `DhlParcelException` and take it from there.
Inspect the response, log the details or whatever you need to do.

**Comment by jacobdekeizer** [comment]
@mvdnbrk I understand and it's fine by me, but a combination of both would be the best imo

**Comment by mvdnbrk** [comment]
Closing this in favor of #47. Thanks @jacobdekeizer

**Pull request closed without merging**
