### PR TITLE
Add support for evening delivery and extra assurance

### PR DESCRIPTION
**Pull request by bastiaansenglenn**
## Description

Adding the insured shipping option

## Motivation and context

I want to create insured shipments, but there was no option available. In the documentation of DHLPARCEL is described that you just need to post INS as a option

## How has this been tested?

Yes, tests are created and tested

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

I hope you also think this is helpful and this PR can be merged! :)

Thanks in advance!

### CODE REVIEW

**Comment by bastiaansenglenn** [comment]
If you have any questions, please contact me.

**Comment by stonjohnsson** [comment]
Can you approve & merge this @mvdnbrk ? :-)

**Comment by mvdnbrk** [comment]
Shouldn't there be an input of type `number` instead of a `boolean` ?

```json
      {
        "key": "INS",
        "description": "All risks insurance",
        "rank": 12,
        "code": 0,
        "optionType": "SERVICE_OPTION",
        "inputType": "number",
        "exclusions": [
          {
            "key": "INS_DUE",
            "rank": 13,
            "code": 0,
            "inputType": "number",
            "optionType": "SERVICE_OPTION"
          },
          {
            "key": "BP",
            "rank": 3,
            "code": 91,
            "optionType": "DELIVERY_OPTION"
          },
          {
            "key": "NO_TT",
            "rank": 30,
            "code": 0,
            "optionType": "DELIVERY_OPTION"
          }
        ]
      }
```

https://api-gw.dhlparcel.nl/docs/#/Capabilities

**Comment by bastiaansenglenn** [comment]
@mvdnbrk I changed the option INS to EA (extra assurance) because not everybody has the INS option enabled in our case. I thought I needed the INS option but instead I should have used the EA option.

I also added the EVE option, I suppose that was also requested in a closed issue.

These 2 options should both be booleans. We have created multiple shipments with this code and the shipments were created without failing.

When you think i forgot something or did something wrong, please let me know!

Thanks in advance!

**Comment by mvdnbrk** [comment]
Thanks!

**Pull request merged**
