### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by timo002**
Updated the sender tag for company. Using `company_name` gave an error.

## Description

Changes `company_name` to `company`
## Motivation and context

The API returned an error.

## How has this been tested?

Running to code trying to create a shipment in sandbox mode.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked.

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] If my change requires a change to the documentation, I have updated it accordingly.
- [x] My code follows the code style of this project.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by mvdnbrk** [comment]
`company` is just an alias which sets the `company_name` attribute.
This has also been tested.

Please can you post the error returned from the API?

**Comment by mvdnbrk** [comment]
Closing this for now.

**Comment by timo002** [comment]
Error message when using `company_name` in the sender field.
```
Error executing API call: The supplied body could not be parsed correctly, see the details field for additional information.
```
In the Recipient class there is `addressToArray()` methods which works with the `company` key. Making the proposed change does not give me this error.

**Comment by mvdnbrk** [comment]
Which version are you using? I guess it is <6.0.
Please update the package to the latest version.

**Pull request closed without merging**
