### PR TITLE
Implement ResourceCollection

### PR DESCRIPTION
**Pull request by jacobdekeizer**
@mvdnbrk I implemented a ResouceCollection so we can easily create more collections when necessary. I changed the arrayble and jsonable contracts to a new resource contract. The new ResourceCollection extends the Resource contract. I still need to add tests, but let me know what you think :)

The ResouceCollection base gives the following methods:
```php
$pieces->addItem(new Piece);
$pieces->first();
$pieces->last();
$pieces->getItems();
$pieces->count();
```

### CODE REVIEW

**Comment by mvdnbrk** [comment]
I am not sure about this.

Why should we write and test all the logic for a collection ourselves and reinvent the wheel.

The `tightenco/collect` package is all ready used and works like a charm.

**Comment by jacobdekeizer** [comment]
@mvdnbrk This collection is strict typed and the collect package has a lot of functions we don't need. I am not a big fan of the collect package and rather use the native functions :)

**Comment by mvdnbrk** [comment]
If you would like to go that path I would prefer to have a `Mvdnbrk\DhlParcel\Support\Collection` class with all the basic methods like `first`, `last` etc. On a lower level it will be easier to maintain and test. A resource collection could extend the `Collection` class.

**Comment by jacobdekeizer** [comment]
The only use case is as a resource collection. If we make a generic `Collection` class we can't have strict return types of interface `Resource` and I think it will be harder to maintain a generic `Collection` class which is going to be extend by the `ResourceCollection` class. The only thing we have need when creating a new ResourceCollection is to make a class which extends `ResourceCollection` and implement an addItem method.

**Comment by mvdnbrk** [comment]
The `first`, `last`, `getItems`, `count` or whatever method we might come up with are all the same functionality whether is a `Collection` class or a `ResourceCollection` class.

The `ResourceCollection` class can extend the `Collection` class and overwrite the `addItem` class so that method accepts only a certain type of object.

A collection is just holding an array of items. Nothing more, nothing less.

**Comment by jacobdekeizer** [comment]
I will refactor it tomorrow :)

**Comment by mvdnbrk** [comment]
Easiest solution would be:

```
<?php

namespace Mvdnbrk\DhlParcel\Support;

use Tightenco\Collect\Support\Collection;

class ResourceCollection extends Collection
{
     // custom logic
}
```

```
<?php

namespace Mvdnbrk\DhlParcel\Recources;

class Pieces extends ResourceCollection
{
}
```

**Comment by mvdnbrk** [comment]
Closing this for now,

**Pull request closed without merging**
